// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dropwizard.proto

package io.dropwizard.jersey.protobuf.protos;

public final class DropwizardProtosTest {
  private DropwizardProtosTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dropwizard.Example)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code dropwizard.Example}
   */
  public  static final class Example extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dropwizard.Example)
      ExampleOrBuilder {
    // Use Example.newBuilder() to construct.
    private Example(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Example() {
      id_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Example(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.internal_static_dropwizard_Example_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.internal_static_dropwizard_Example_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.class, io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example)) {
        return super.equals(obj);
      }
      io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example other = (io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dropwizard.Example}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dropwizard.Example)
        io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.ExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.internal_static_dropwizard_Example_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.internal_static_dropwizard_Example_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.class, io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.Builder.class);
      }

      // Construct using io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.internal_static_dropwizard_Example_descriptor;
      }

      public io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example getDefaultInstanceForType() {
        return io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.getDefaultInstance();
      }

      public io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example build() {
        io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example buildPartial() {
        io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example result = new io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example) {
          return mergeFrom((io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example other) {
        if (other == io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dropwizard.Example)
    }

    // @@protoc_insertion_point(class_scope:dropwizard.Example)
    private static final io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example();
    }

    public static io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Example>
        PARSER = new com.google.protobuf.AbstractParser<Example>() {
      public Example parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Example(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Example> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Example> getParserForType() {
      return PARSER;
    }

    public io.dropwizard.jersey.protobuf.protos.DropwizardProtosTest.Example getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dropwizard_Example_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dropwizard_Example_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dropwizard.proto\022\ndropwizard\"\025\n\007Exampl" +
      "e\022\n\n\002id\030\001 \001(\003B>\n$io.dropwizard.jersey.pr" +
      "otobuf.protosB\024DropwizardProtosTestH\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dropwizard_Example_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dropwizard_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dropwizard_Example_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
